package ru.rybinsk.silhouette.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import ru.rybinsk.silhouette.model.PersonalData;
import ru.rybinsk.silhouette.model.PersonalDataExample;

public interface PersonalDataMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int countByExample(PersonalDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int deleteByExample(PersonalDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int insert(PersonalData record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int insertSelective(PersonalData record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    List<PersonalData> selectByExample(PersonalDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    PersonalData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PersonalData record, @Param("example") PersonalDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int updateByExample(@Param("record") PersonalData record, @Param("example") PersonalDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonalData record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table personal_data
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonalData record);

    List<PersonalData> selectAllFull();

    List<PersonalData> selectByExampleFull(PersonalDataExample pde);

    PersonalData selectByPrimaryKeyFull(Integer id);
}