package ru.rybinsk.silhouette.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ru.rybinsk.silhouette.model.Simulator;
import ru.rybinsk.silhouette.model.SimulatorExample;

public interface SimulatorMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int countByExample(SimulatorExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int deleteByExample(SimulatorExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int insert(Simulator record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int insertSelective(Simulator record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    List<Simulator> selectByExample(SimulatorExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    Simulator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Simulator record, @Param("example") SimulatorExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int updateByExample(@Param("record") Simulator record, @Param("example") SimulatorExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Simulator record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table simulator
     * @mbggenerated
     */
    int updateByPrimaryKey(Simulator record);
}