package ru.rybinsk.silhouette.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ru.rybinsk.silhouette.model.Subscription;
import ru.rybinsk.silhouette.model.SubscriptionExample;

public interface SubscriptionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int countByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int deleteByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int insert(Subscription record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int insertSelective(Subscription record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    List<Subscription> selectByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    Subscription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Subscription record, @Param("example") SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int updateByExample(@Param("record") Subscription record, @Param("example") SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subscription record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table subscription
     * @mbggenerated
     */
    int updateByPrimaryKey(Subscription record);
}