package ru.rybinsk.silhouette.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ru.rybinsk.silhouette.model.TimeTable;
import ru.rybinsk.silhouette.model.TimeTableExample;

public interface TimeTableMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int countByExample(TimeTableExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int deleteByExample(TimeTableExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int insert(TimeTable record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int insertSelective(TimeTable record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    List<TimeTable> selectByExample(TimeTableExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    TimeTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TimeTable record, @Param("example") TimeTableExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int updateByExample(@Param("record") TimeTable record, @Param("example") TimeTableExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TimeTable record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table time_table
     * @mbggenerated
     */
    int updateByPrimaryKey(TimeTable record);
}