package ru.rybinsk.silhouette.model;

import java.io.Serializable;

public class Ambry extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ambry.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ambry
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ambry.Name
     *
     * @return the value of ambry.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ambry.Name
     *
     * @param name the value for ambry.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}