package ru.rybinsk.silhouette.model;

import java.io.Serializable;
import java.util.Date;

public class PersonalData extends BaseModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.First_Name
     * 
     * @mbggenerated
     */
    private String firstName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.Middle_Name
     * 
     * @mbggenerated
     */
    private String middleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.Last_Name
     * 
     * @mbggenerated
     */
    private String lastName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.Birthday
     * 
     * @mbggenerated
     */
    private Date birthday;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column personal_data.Phone1
     * 
     * @mbggenerated
     */
    private String phone1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column personal_data.Phone2
     * 
     * @mbggenerated
     */
    private String phone2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.Contract_Number
     * 
     * @mbggenerated
     */
    private String contractNumber;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column personal_data.Active
     * 
     * @mbggenerated
     */
    private Boolean active;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column personal_data.Note
     * 
     * @mbggenerated
     */
    private String note;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * personal_data.Ambry_Id
     * 
     * @mbggenerated
     */
    private Integer ambryId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table personal_data
     * 
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.First_Name
     * 
     * @return the value of personal_data.First_Name
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.First_Name
     * 
     * @param firstName
     *            the value for personal_data.First_Name
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Middle_Name
     * 
     * @return the value of personal_data.Middle_Name
     * @mbggenerated
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Middle_Name
     * 
     * @param middleName
     *            the value for personal_data.Middle_Name
     * @mbggenerated
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Last_Name
     * 
     * @return the value of personal_data.Last_Name
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Last_Name
     * 
     * @param lastName
     *            the value for personal_data.Last_Name
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Birthday
     * 
     * @return the value of personal_data.Birthday
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Birthday
     * 
     * @param birthday
     *            the value for personal_data.Birthday
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Phone1
     * 
     * @return the value of personal_data.Phone1
     * @mbggenerated
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Phone1
     * 
     * @param phone1
     *            the value for personal_data.Phone1
     * @mbggenerated
     */
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Phone2
     * 
     * @return the value of personal_data.Phone2
     * @mbggenerated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Phone2
     * 
     * @param phone2
     *            the value for personal_data.Phone2
     * @mbggenerated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Contract_Number
     * 
     * @return the value of personal_data.Contract_Number
     * @mbggenerated
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Contract_Number
     * 
     * @param contractNumber
     *            the value for personal_data.Contract_Number
     * @mbggenerated
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Active
     * 
     * @return the value of personal_data.Active
     * @mbggenerated
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Active
     * 
     * @param active
     *            the value for personal_data.Active
     * @mbggenerated
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Note
     * 
     * @return the value of personal_data.Note
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Note
     * 
     * @param note
     *            the value for personal_data.Note
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * personal_data.Ambry_Id
     * 
     * @return the value of personal_data.Ambry_Id
     * @mbggenerated
     */
    public Integer getAmbryId() {
        return ambryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * personal_data.Ambry_Id
     * 
     * @param ambryId
     *            the value for personal_data.Ambry_Id
     * @mbggenerated
     */
    public void setAmbryId(Integer ambryId) {
        this.ambryId = ambryId;
    }

    private Subscription subscription;

    public Subscription getSubscription() {
        return subscription;
    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }

    public String getFio() {
        return lastName + " " + firstName + " " + middleName;
    }

    @Override
    public boolean equals(Object obj) {
        if (id.equals(((BaseModel) obj).getId())) {
            return true;
        }
        return false;
    }
}