package ru.rybinsk.silhouette.model;

import java.io.Serializable;

public class Simulator extends BaseModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Name
     * @mbggenerated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Duration_Type
     * @mbggenerated
     */
    private Integer durationType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Cost
     * @mbggenerated
     */
    private Float cost;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Note
     * @mbggenerated
     */
    private String note;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Ord
     * @mbggenerated
     */
    private Integer ord;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column simulator.Activity
     * @mbggenerated
     */
    private Boolean activity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table simulator
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Name
     * @return  the value of simulator.Name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Name
     * @param name  the value for simulator.Name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Duration_Type
     * @return  the value of simulator.Duration_Type
     * @mbggenerated
     */
    public Integer getDurationType() {
        return durationType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Duration_Type
     * @param durationType  the value for simulator.Duration_Type
     * @mbggenerated
     */
    public void setDurationType(Integer durationType) {
        this.durationType = durationType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Cost
     * @return  the value of simulator.Cost
     * @mbggenerated
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Cost
     * @param cost  the value for simulator.Cost
     * @mbggenerated
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Note
     * @return  the value of simulator.Note
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Note
     * @param note  the value for simulator.Note
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Ord
     * @return  the value of simulator.Ord
     * @mbggenerated
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Ord
     * @param ord  the value for simulator.Ord
     * @mbggenerated
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column simulator.Activity
     * @return  the value of simulator.Activity
     * @mbggenerated
     */
    public Boolean getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column simulator.Activity
     * @param activity  the value for simulator.Activity
     * @mbggenerated
     */
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
}