package ru.rybinsk.silhouette.model;

import java.io.Serializable;
import java.util.Date;

public class Subscription extends BaseModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Subscription_Number
     * 
     * @mbggenerated
     */
    private String subscriptionNumber;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column subscription.Period
     * 
     * @mbggenerated
     */
    private Integer period = 0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column subscription.Type
     * 
     * @mbggenerated
     */
    private Integer type = 0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column subscription.State
     * 
     * @mbggenerated
     */
    private Integer state = 0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Date_From
     * 
     * @mbggenerated
     */
    private Date dateFrom;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column subscription.Date_To
     * 
     * @mbggenerated
     */
    private Date dateTo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Participation_Number
     * 
     * @mbggenerated
     */
    private Float participationNumber;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Participation_Number_Present
     * 
     * @mbggenerated
     */
    private Float participationNumberPresent;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Reason_Reject
     * 
     * @mbggenerated
     */
    private String reasonReject;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * subscription.Personal_Data_Id
     * 
     * @mbggenerated
     */
    private Integer personalDataId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table subscription
     * 
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Subscription_Number
     * 
     * @return the value of subscription.Subscription_Number
     * @mbggenerated
     */
    public String getSubscriptionNumber() {
        return subscriptionNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Subscription_Number
     * 
     * @param subscriptionNumber
     *            the value for subscription.Subscription_Number
     * @mbggenerated
     */
    public void setSubscriptionNumber(String subscriptionNumber) {
        this.subscriptionNumber = subscriptionNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Period
     * 
     * @return the value of subscription.Period
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Period
     * 
     * @param period
     *            the value for subscription.Period
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Type
     * 
     * @return the value of subscription.Type
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Type
     * 
     * @param type
     *            the value for subscription.Type
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.State
     * 
     * @return the value of subscription.State
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.State
     * 
     * @param state
     *            the value for subscription.State
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Date_From
     * 
     * @return the value of subscription.Date_From
     * @mbggenerated
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Date_From
     * 
     * @param dateFrom
     *            the value for subscription.Date_From
     * @mbggenerated
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Date_To
     * 
     * @return the value of subscription.Date_To
     * @mbggenerated
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Date_To
     * 
     * @param dateTo
     *            the value for subscription.Date_To
     * @mbggenerated
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Participation_Number
     * 
     * @return the value of subscription.Participation_Number
     * @mbggenerated
     */
    public Float getParticipationNumber() {
        return participationNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Participation_Number
     * 
     * @param participationNumber
     *            the value for subscription.Participation_Number
     * @mbggenerated
     */
    public void setParticipationNumber(Float participationNumber) {
        this.participationNumber = participationNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Participation_Number_Present
     * 
     * @return the value of subscription.Participation_Number_Present
     * @mbggenerated
     */
    public Float getParticipationNumberPresent() {
        return participationNumberPresent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Participation_Number_Present
     * 
     * @param participationNumberPresent
     *            the value for subscription.Participation_Number_Present
     * @mbggenerated
     */
    public void setParticipationNumberPresent(Float participationNumberPresent) {
        this.participationNumberPresent = participationNumberPresent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Reason_Reject
     * 
     * @return the value of subscription.Reason_Reject
     * @mbggenerated
     */
    public String getReasonReject() {
        return reasonReject;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Reason_Reject
     * 
     * @param reasonReject
     *            the value for subscription.Reason_Reject
     * @mbggenerated
     */
    public void setReasonReject(String reasonReject) {
        this.reasonReject = reasonReject;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * subscription.Personal_Data_Id
     * 
     * @return the value of subscription.Personal_Data_Id
     * @mbggenerated
     */
    public Integer getPersonalDataId() {
        return personalDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * subscription.Personal_Data_Id
     * 
     * @param personalDataId
     *            the value for subscription.Personal_Data_Id
     * @mbggenerated
     */
    public void setPersonalDataId(Integer personalDataId) {
        this.personalDataId = personalDataId;
    }
}