package ru.rybinsk.silhouette.model;

import java.io.Serializable;
import java.util.Date;

public class TimeTable extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column time_table.Date
     * 
     * @mbggenerated
     */
    private Date date;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column time_table.Time
     * 
     * @mbggenerated
     */
    private String time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * time_table.Simulator_Id
     * 
     * @mbggenerated
     */
    private Integer simulatorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * time_table.Personal_Data_Id
     * 
     * @mbggenerated
     */
    private Integer personalDataId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column time_table.Note
     * 
     * @mbggenerated
     */
    private String note;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * time_table.Printed_Act
     * 
     * @mbggenerated
     */
    private Boolean printedAct = false;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table time_table
     * 
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Date
     * 
     * @return the value of time_table.Date
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column time_table.Date
     * 
     * @param date
     *            the value for time_table.Date
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Time
     * 
     * @return the value of time_table.Time
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column time_table.Time
     * 
     * @param time
     *            the value for time_table.Time
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Simulator_Id
     * 
     * @return the value of time_table.Simulator_Id
     * @mbggenerated
     */
    public Integer getSimulatorId() {
        return simulatorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * time_table.Simulator_Id
     * 
     * @param simulatorId
     *            the value for time_table.Simulator_Id
     * @mbggenerated
     */
    public void setSimulatorId(Integer simulatorId) {
        this.simulatorId = simulatorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Personal_Data_Id
     * 
     * @return the value of time_table.Personal_Data_Id
     * @mbggenerated
     */
    public Integer getPersonalDataId() {
        return personalDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * time_table.Personal_Data_Id
     * 
     * @param personalDataId
     *            the value for time_table.Personal_Data_Id
     * @mbggenerated
     */
    public void setPersonalDataId(Integer personalDataId) {
        this.personalDataId = personalDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Note
     * 
     * @return the value of time_table.Note
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column time_table.Note
     * 
     * @param note
     *            the value for time_table.Note
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * time_table.Printed_Act
     * 
     * @return the value of time_table.Printed_Act
     * @mbggenerated
     */
    public Boolean getPrintedAct() {
        return printedAct;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * time_table.Printed_Act
     * 
     * @param printedAct
     *            the value for time_table.Printed_Act
     * @mbggenerated
     */
    public void setPrintedAct(Boolean printedAct) {
        this.printedAct = printedAct;
    }

    private PersonalData personalData;
    private Simulator simulator;

    public PersonalData getPersonalData() {
        return personalData;
    }

    public void setPersonalData(PersonalData personalData) {
        this.personalData = personalData;
    }

    public Simulator getSimulator() {
        return simulator;
    }

    public void setSimulator(Simulator simulator) {
        this.simulator = simulator;
    }
}